# 1.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

## Часть 1 (19 баллов)

1) Импортировать numpy и написать версию (1 балл)

In [90]:
import numpy as np

In [5]:
np.__version__
np.random.seed(0)

2) Создать нулевой вектор размера 10 (1 балл)

In [7]:
a = np.full(shape=10,fill_value=0)
print(a)

[0 0 0 0 0 0 0 0 0 0]


3) Создать вектор заполненный 7-ами размера 7 (2 балла)


In [0]:
b = np.full(shape=7,fill_value=7)
print(b)

4) Создать вектор заполненный четными числами от 10 до 100 включительно (2 балла)

In [9]:
c = np.arange(start=10,stop=110,step=10)
print(c)

[ 10  20  30  40  50  60  70  80  90 100]


5) Создать массив случайных чисел и развернуть его задом наперёд (4 балла)

In [8]:
d = np.random.randint(10, size=6)
print(d)
e = d[::-1]
print(e)

[1 7 3 1 3 6]
[6 3 1 3 7 1]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (4 балла)

In [13]:
f = np.arange(9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх. (5 баллов)

In [30]:
g = np.eye(4,k=1,dtype='int')
print(g)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


## Часть 2 (26 баллов)

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки. (2 балла)

In [39]:
h = np.full(shape=16,fill_value=7).reshape(4,4)
h_a = np.arange(4) + 1
np.fill_diagonal(h, h_a)
print(h)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках. (2 балла)

In [27]:
i_a = np.arange(5)
i = np.tile(i_a, (5, 1))
#or i = np.zeros((5,5))
#   i += i_a
print(i)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки (3 балла)

In [45]:
j = np.random.randint(10, size=100).reshape(10,10)
print(j)
print()
j = np.apply_along_axis( lambda x: x - x.mean(), axis=1, arr=j)
print(j)

[[3 4 1 1 0 7 8 4 3 5]
 [6 3 2 9 8 1 4 0 8 3]
 [9 5 5 1 7 8 6 4 7 3]
 [5 3 6 4 7 3 0 5 9 3]
 [7 5 5 8 0 8 3 6 9 3]
 [2 7 0 3 0 3 6 1 9 2]
 [9 4 9 1 3 2 4 9 7 4]
 [9 4 1 2 7 2 3 9 7 6]
 [6 2 3 6 0 8 0 7 6 5]
 [9 6 5 2 7 1 9 2 2 5]]
[[-0.6  0.4 -2.6 -2.6 -3.6  3.4  4.4  0.4 -0.6  1.4]
 [ 1.6 -1.4 -2.4  4.6  3.6 -3.4 -0.4 -4.4  3.6 -1.4]
 [ 3.5 -0.5 -0.5 -4.5  1.5  2.5  0.5 -1.5  1.5 -2.5]
 [ 0.5 -1.5  1.5 -0.5  2.5 -1.5 -4.5  0.5  4.5 -1.5]
 [ 1.6 -0.4 -0.4  2.6 -5.4  2.6 -2.4  0.6  3.6 -2.4]
 [-1.3  3.7 -3.3 -0.3 -3.3 -0.3  2.7 -2.3  5.7 -1.3]
 [ 3.8 -1.2  3.8 -4.2 -2.2 -3.2 -1.2  3.8  1.8 -1.2]
 [ 4.  -1.  -4.  -3.   2.  -3.  -2.   4.   2.   1. ]
 [ 1.7 -2.3 -1.3  1.7 -4.3  3.7 -4.3  2.7  1.7  0.7]
 [ 4.2  1.2  0.2 -2.8  2.2 -3.8  4.2 -2.8 -2.8  0.2]]


4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца (4 балла)

In [79]:
j = np.random.randint(10, size=100).reshape(10,10)
print(j)
print()
j_m = np.median(j,axis=0)
print('{0} - median'.format(j_m))
print()
j = np.apply_along_axis( lambda x: x - j_m, axis=1, arr=j)
print(j)

[[0 8 2 5 4 2 4 2 0 1]
 [5 5 8 0 0 5 7 3 6 0]
 [2 0 5 1 7 3 2 3 2 3]
 [7 7 1 4 6 7 0 0 6 4]
 [4 5 1 2 6 8 2 9 9 5]
 [5 8 5 9 1 9 4 6 9 8]
 [0 5 6 0 6 0 6 7 1 1]
 [5 0 6 4 4 4 7 2 1 4]
 [9 8 4 4 7 0 7 8 9 9]
 [5 2 6 9 5 6 5 3 3 0]]

[5.  5.  5.  4.  5.5 4.5 4.5 3.  4.5 3.5] - median

[[-5.   3.  -3.   1.  -1.5 -2.5 -0.5 -1.  -4.5 -2.5]
 [ 0.   0.   3.  -4.  -5.5  0.5  2.5  0.   1.5 -3.5]
 [-3.  -5.   0.  -3.   1.5 -1.5 -2.5  0.  -2.5 -0.5]
 [ 2.   2.  -4.   0.   0.5  2.5 -4.5 -3.   1.5  0.5]
 [-1.   0.  -4.  -2.   0.5  3.5 -2.5  6.   4.5  1.5]
 [ 0.   3.   0.   5.  -4.5  4.5 -0.5  3.   4.5  4.5]
 [-5.   0.   1.  -4.   0.5 -4.5  1.5  4.  -3.5 -2.5]
 [ 0.  -5.   1.   0.  -1.5 -0.5  2.5 -1.  -3.5  0.5]
 [ 4.   3.  -1.   0.   1.5 -4.5  2.5  5.   4.5  5.5]
 [ 0.  -3.   1.   5.  -0.5  1.5  0.5  0.  -1.5 -3.5]]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7. (4 балла) 

In [94]:
j = np.random.randint(10, size=25).reshape(5,5)
print(j)
print()
j_max = j.max(axis = 1)
print('{0} - max'.format(j_max))
j_min = j.min(axis = 1)
print('{0} - min'.format(j_min))
print()
j = np.column_stack((np.column_stack((j, j_max)),j_min))
print(j)

[[3 4 1 0 9]
 [9 3 9 3 4]
 [6 5 7 1 5]
 [7 6 6 6 1]
 [8 4 2 0 2]]

[9 9 7 7 8] - max
[0 3 1 1 0] - min

[[3 4 1 0 9 9 0]
 [9 3 9 3 4 9 3]
 [6 5 7 1 5 7 1]
 [7 6 6 6 1 7 1]
 [8 4 2 0 2 8 0]]


6) Вектор чисел от 1 до 50 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  (6 баллов)

In [97]:
k = np.arange(50) + 1
print(k)
print()
k_odd = np.asmatrix(k[::2]).reshape(5,5)
print(k_odd)
print()
k_even = np.asmatrix(k[1::2]).reshape(5,5)
print(k_even)
print()
k_mul = k_even * k_odd
print(k_mul) 
print()
k_det = np.linalg.det(k_mul)
print('{0} - determinant'.format(k_det))
if k_det != 0:
    print(k_mul.I)
else:
    print('Обратной матрицы нет, т.к определитель равен 0')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]

0.0 - determinant
Обратной матрицы нет, т.к определитель равен 0


7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. (5 баллов)

In [82]:
l = np.zeros((8,8), dtype=int)
l[1::2,::2] = 1
l[::2,1::2] = 1
print(l)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
